Repository FlourishHealth/ferns-ui, pull requests merged in 2024-08, with the labels that each got.

#701 Add getIsoDate func for null to undefined
  packages/ui/src/DateUtilities.tsx
Labels: enhancement, Review effort [1-5]: 2

#704 TextField set focused state
  packages/ui/src/TextField.tsx
Labels: enhancement, Review effort [1-5]: 1

#705 BooleanField: add useEffect
  packages/ui/src/BooleanField.tsx
Labels: enhancement, Review effort [1-5]: 2

#706 Button useMemo for style
  packages/ui/src/Button.tsx
Labels: enhancement, Review effort [1-5]: 2

#708 TextField add prop onFocus
  packages/ui/src/TextField.tsx
Labels: enhancement, Review effort [1-5]: 1

#712 Email, Number, Phone Fields Add useEffect
  packages/ui/src/EmailField.tsx
  packages/ui/src/NumberField.tsx
  packages/ui/src/PhoneNumberField.tsx
Labels: enhancement, Review effort [1-5]: 2

#715 DatetimeField Error Handling Enhancement
  packages/ui/src/DateTimeField.tsx
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#719 Upgrade react-native-drawer-layout
  packages/ui/package.json
  yarn.lock
Labels: dependencies, Review effort [1-5]: 1

#681 Restore CI for demo, delete ui-demo, upgrade deps
  .github/dependabot.yml
  .github/workflows/ui-demo-ci.yml
  README.md
  apps/demo/app/demo/[component].tsx
  apps/demo/app/index.tsx
  apps/demo/demoConfig.tsx
  apps/demo/index.js
  apps/demo/package.json
  apps/demo/stories/EmailField.stories.tsx
  apps/demo/stories/Field.stories.tsx
  apps/demo/stories/SelectField.stories.tsx
  apps/demo/stories/SignatureField.stories.tsx
  apps/demo/stories/TextArea.stories.tsx
  apps/demo/stories/Theme.stories.tsx
  apps/demo/story-config/Field.config.tsx
  apps/demo/story-config/IconButton.config.tsx
  apps/demo/story-config/Pagination.config.tsx
  dependabot.yml
  package.json
  packages/ui-demo/webpack.config.js
  packages/ui/package.json
  syncUiFromUiDemo.js
  yarn.lock
Labels: Review effort [1-5]: 4, enhancement, Bug fix
