Repository FlourishHealth/ferns-ui, pull requests merged in 2024-06, with the labels that each got.

#572 fix AM PM issue
  packages/ui/src/DateTimeActionSheet.tsx
Labels: Review effort [1-5]: 1, Bug fix

#577 fix 12AM hour bug
  packages/ui/src/DateTimeActionSheet.tsx
Labels: Review effort [1-5]: 2, Bug fix

#576 TapToEdit - add useEffect for initialValue handling
  packages/ui/src/TapToEdit.tsx
Labels: enhancement, Review effort [1-5]: 2

#585 Radio and Radio Field
  apps/demo/stories/Radio.stories.tsx
  apps/demo/stories/RadioField.stories.tsx
  apps/demo/stories/index.tsx
  apps/demo/story-config/Radio.config.tsx
  apps/demo/story-config/RadioField.config.tsx
  apps/demo/ui-types-documentation.json
  packages/ui/src/Common.ts
  packages/ui/src/Radio.tsx
  packages/ui/src/RadioField.tsx
Labels: enhancement, Review effort [1-5]: 3, Tests

#587 Fix remove Radio story
  apps/demo/demoConfig.tsx
  apps/demo/stories/index.tsx
  apps/demo/story-config/index.ts
  packages/ui/src/RadioField.tsx
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#586 Spinner
  apps/demo/stories/Spinner.stories.tsx
  apps/demo/story-config/Spinner.config.tsx
  packages/ui/src/Common.ts
  packages/ui/src/Page.tsx
  packages/ui/src/Spinner.tsx
  packages/ui/src/Theme.tsx
Labels: Review effort [1-5]: 4, enhancement, Tests

#583 Migrate segmented control
  apps/demo/app/demo/[component].tsx
  apps/demo/stories/SegmentedControl.stories.tsx
  apps/demo/story-config/SegmentedControl.config.tsx
  packages/ui/src/Common.ts
  packages/ui/src/SegmentedControl.tsx
  packages/ui/src/Spinner.tsx
  packages/ui/src/SplitPage.tsx
  packages/ui/src/Theme.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#580 Fix up text, finish Link
  apps/demo/stories/Text.stories.tsx
  packages/ui/src/Banner.tsx
  packages/ui/src/Button.tsx
  packages/ui/src/CheckBox.tsx
  packages/ui/src/Common.ts
  packages/ui/src/ErrorPage.tsx
  packages/ui/src/Field.tsx
  packages/ui/src/Heading.tsx
  packages/ui/src/Hyperlink.tsx
  packages/ui/src/IconButton.tsx
  packages/ui/src/Link.tsx
  packages/ui/src/TapToEdit.tsx
  packages/ui/src/Text.tsx
  packages/ui/src/Toast.tsx
  packages/ui/src/WithLabel.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#589 Boolean Field
  apps/demo/stories/BooleanField.stories.tsx
  apps/demo/stories/Switch.stories.tsx
  apps/demo/stories/index.ts
  apps/demo/stories/index.tsx
  apps/demo/story-config/BooleanField.config.tsx
  apps/demo/ui-types-documentation.json
  packages/ui/src/BooleanField.tsx
  packages/ui/src/Common.ts
  packages/ui/src/Field.tsx
  packages/ui/src/Switch.tsx
  packages/ui/src/index.tsx
Labels: enhancement, Review effort [1-5]: 3, Other

#593 Modal and Button
  apps/demo/stories/Button.stories.tsx
  apps/demo/stories/Modal.stories.tsx
  apps/demo/story-config/Button.config.tsx
  apps/demo/story-config/Modal.config.tsx
  packages/ui/package.json
  packages/ui/src/Banner.tsx
  packages/ui/src/Button.tsx
  packages/ui/src/Common.ts
  packages/ui/src/DateTimeActionSheet.tsx
  packages/ui/src/DecimalRangeActionSheet.tsx
  packages/ui/src/ErrorPage.tsx
  packages/ui/src/HeightActionSheet.tsx
  packages/ui/src/IconButton.tsx
  packages/ui/src/Modal.tsx
  packages/ui/src/NumberPickerActionSheet.tsx
  packages/ui/src/Page.tsx
  packages/ui/src/Pagination.tsx
  packages/ui/src/Signature.tsx
  packages/ui/src/TapToEdit.tsx
  packages/ui/src/TextFieldNumberActionSheet.tsx
  packages/ui/src/Toast.tsx
Labels: Review effort [1-5]: 4, enhancement, Tests

#596 Signature Field
  apps/demo/stories/SignatureField.stories.tsx
  apps/demo/story-config/SignatureField.config.tsx
  apps/demo/ui-types-documentation.json
  packages/ui/src/Common.ts
  packages/ui/src/Signature.native.tsx
  packages/ui/src/Signature.tsx
  packages/ui/src/SignatureField.tsx
Labels: Review effort [1-5]: 4, enhancement, documentation

#595 Icon Button
  apps/demo/demoConfig.tsx
  apps/demo/package.json
  apps/demo/stories/Button.stories.tsx
  apps/demo/stories/IconButton.stories.tsx
  apps/demo/stories/Tooltip.stories.tsx
  apps/demo/story-config/IconButton.config.tsx
  apps/demo/story-config/index.ts
  apps/demo/ui-types-documentation.json
  packages/ui/src/Avatar.tsx
  packages/ui/src/Banner.tsx
  packages/ui/src/Button.tsx
  packages/ui/src/Common.ts
  packages/ui/src/DateTimeActionSheet.tsx
  packages/ui/src/IconButton.tsx
  packages/ui/src/InfoTooltipButton.tsx
  packages/ui/src/Page.tsx
  packages/ui/src/SplitPage.native.tsx
  packages/ui/src/SplitPage.tsx
  packages/ui/src/TapToEdit.tsx
  packages/ui/src/Toast.tsx
  packages/ui/src/Tooltip.tsx
  packages/ui/src/table/TableHeaderCell.tsx
  packages/ui/src/table/TableRow.tsx
Labels: Review effort [1-5]: 4, enhancement, Bug fix

#602 Multiselectfield
  apps/demo/stories/MultiselectField.stories.tsx
  apps/demo/stories/index.ts
  apps/demo/story-config/MultiselectField.config.tsx
  apps/demo/ui-types-documentation.json
  packages/ui/src/Common.ts
  packages/ui/src/MediaQuery.ts
  packages/ui/src/MultiselectField.tsx
Labels: enhancement, Review effort [1-5]: 3, Tests

#603 Accordion
  apps/demo/demoConfig.tsx
  apps/demo/stories/Accordion.stories.tsx
  apps/demo/stories/index.ts
  apps/demo/story-config/Accordion.config.tsx
  apps/demo/story-config/index.ts
  apps/demo/ui-types-documentation.json
  packages/ui/src/Accordion.tsx
  packages/ui/src/Common.ts
  packages/ui/src/index.tsx
Labels: enhancement, documentation, Review effort [1-5]: 3, Tests

#600 Tooltip and support updates to Button and IconButton
  apps/demo/stories/Button.stories.tsx
  apps/demo/stories/IconButton.stories.tsx
  apps/demo/stories/Modal.stories.tsx
  apps/demo/stories/Tooltip.stories.tsx
  apps/demo/story-config/Button.config.tsx
  apps/demo/story-config/IconButton.config.tsx
  apps/demo/story-config/Tooltip.config.tsx
  apps/demo/ui-types-documentation.json
  packages/ui/src/Button.tsx
  packages/ui/src/Common.ts
  packages/ui/src/IconButton.tsx
  packages/ui/src/Tooltip.tsx
Labels: Review effort [1-5]: 4, enhancement, Tests

#604 Remove types
  .gitignore
  apps/demo/ui-types-documentation.json
  packages/ui/out.json
Labels: Review effort [1-5]: 4, enhancement, documentation, Tests, configuration changes, Miscellaneous

#606 Fix up dev/demo navigation
  apps/demo/app/demo/[component].tsx
  apps/demo/app/demo/_layout.tsx
  apps/demo/app/dev/[component].tsx
  apps/demo/app/dev/_layout.tsx
  apps/demo/components/DemoHomePage.tsx
  apps/demo/components/DevHomePage.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix
