Repository FlourishHealth/ferns-ui, pull requests merged in 2024-07, with the labels that each got.

#607 Check Box, Table Button Icon, Table Boolean, Table Date
  apps/demo/stories/CheckBox.stories.tsx
  apps/demo/stories/TableBadge.stories.tsx
  apps/demo/stories/TableBoolean.stories.tsx
  apps/demo/stories/TableDate.stories.tsx
  apps/demo/stories/TableIconButton.stories.tsx
  apps/demo/stories/TableTitle.stories.tsx
  apps/demo/stories/index.ts
  apps/demo/story-config/CheckBox.config.tsx
  apps/demo/story-config/TableBadge.config.tsx
  apps/demo/story-config/TableBoolean.config.tsx
  apps/demo/story-config/TableDate.config.tsx
  apps/demo/story-config/TableIconButton.config.tsx
  apps/demo/story-config/TableTitle.config.tsx
  packages/ui/src/CheckBox.tsx
  packages/ui/src/Common.ts
  packages/ui/src/Field.tsx
  packages/ui/src/MultiselectField.tsx
  packages/ui/src/Theme.tsx
  packages/ui/src/table/Table.tsx
  packages/ui/src/table/TableBadge.tsx
  packages/ui/src/table/TableBoolean.tsx
  packages/ui/src/table/TableDate.tsx
  packages/ui/src/table/TableIconButton.tsx
  packages/ui/src/table/TableTitle.tsx
Labels: Review effort [1-5]: 4, enhancement, Tests, Other

#601 Text field new UI
  apps/demo/stories/TextField.stories.tsx
  apps/demo/story-config/TextField.config.tsx
  apps/demo/ui-types-documentation.json
  packages/ui/src/Common.ts
  packages/ui/src/CustomSelect.tsx
  packages/ui/src/Field.tsx
  packages/ui/src/MobileAddressAutoComplete.tsx
  packages/ui/src/TextField.tsx
  packages/ui/src/UnifiedAddressAutoComplete.tsx
  packages/ui/src/WebAddressAutocomplete.tsx
Labels: enhancement, Review effort [1-5]: 3, Tests

#605 Add Toast
  apps/demo/stories/Toast.stories.tsx
  packages/ui/src/Common.ts
  packages/ui/src/FernsProvider.tsx
  packages/ui/src/Modal.tsx
  packages/ui/src/Toast.tsx
Labels: Review effort [1-5]: 4, enhancement, Bug fix

#611 Field Elements
  apps/demo/ui-types-documentation.json
  packages/ui/src/FieldElements/FieldError.tsx
  packages/ui/src/FieldElements/FieldHelperText.tsx
  packages/ui/src/FieldElements/FieldTitle.tsx
  packages/ui/src/FieldElements/index.tsx
  packages/ui/src/TextField.tsx
  packages/ui/src/table/TableDate.tsx
Labels: Review effort [1-5]: 4, enhancement, documentation, Tests, configuration changes

#613 SelectField
  apps/demo/stories/SelectField.stories.tsx
  apps/demo/story-config/SelectField.config.tsx
  packages/ui/src/Common.ts
  packages/ui/src/CustomSelect.tsx
  packages/ui/src/Field.tsx
  packages/ui/src/MediaQuery.ts
  packages/ui/src/PickerSelect.tsx
  packages/ui/src/SelectField.tsx
  packages/ui/src/SelectList.tsx
  packages/ui/src/TimezonePicker.tsx
  packages/ui/src/index.tsx
Labels: Review effort [1-5]: 4, enhancement, documentation, Tests, configuration changes, Miscellaneous

#614 Fix build errors
  packages/ui/src/Common.ts
  packages/ui/src/DateTimeActionSheet.tsx
  packages/ui/src/IconButton.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#612 New avatar
  .DS_Store
  apps/.DS_Store
  apps/demo/package.json
  apps/demo/stories/Avatar.stories.tsx
  apps/demo/story-config/Avatar.config.tsx
  packages/ui/jest-setup.js
  packages/ui/package.json
  packages/ui/src/Avatar.tsx
  packages/ui/src/Common.ts
  packages/ui/src/icons/MobileIcon.tsx
  packages/ui/src/icons/OfflineIcon.tsx
  packages/ui/src/icons/OnlineIcon.tsx
  packages/ui/src/icons/OutOfficeIcon.tsx
  packages/ui/src/icons/index.ts
  packages/ui/tsconfig.json
  yarn.lock
Labels: dependencies, Review effort [1-5]: 4, enhancement, Tests

#618 Update theme story, fix tsc issues in demo
  .github/workflows/ui-ci.yml
  .github/workflows/ui-demo-ci.yml
  apps/demo/app/demo/[component].tsx
  apps/demo/demoConfig.tsx
  apps/demo/package.json
  apps/demo/stories/Box.stories.tsx
  apps/demo/stories/Card.stories.tsx
  apps/demo/stories/Link.stories.tsx
  apps/demo/stories/Mask.stories.tsx
  apps/demo/stories/SplitPage.stories.tsx
  apps/demo/stories/Table.stories.tsx
  apps/demo/stories/Theme.stories.tsx
  apps/demo/stories/index.ts
  apps/demo/story-config/Link.config.tsx
  apps/demo/story-config/Mask.config.tsx
  apps/demo/story-config/SplitPage.config.tsx
  apps/demo/story-config/Switch.config.tsx
  apps/demo/story-config/Theme.config.tsx
  apps/demo/story-config/index.ts
  packages/ui/src/Box.tsx
  packages/ui/src/Theme.tsx
  yarn.lock
Labels: Review effort [1-5]: 4, enhancement, Tests, configuration changes

#621 Add Box accessibility requirements if onClick is provided
  packages/ui/src/Box.tsx
  packages/ui/src/Common.ts
Labels: enhancement, Review effort [1-5]: 2

#626 Fix Theme typing
  packages/ui/src/ActionSheet.tsx
  packages/ui/src/Avatar.tsx
  packages/ui/src/Badge.tsx
  packages/ui/src/Box.tsx
  packages/ui/src/Button.tsx
  packages/ui/src/Common.ts
  packages/ui/src/DateTimeActionSheet.tsx
  packages/ui/src/DateUtilities.tsx
  packages/ui/src/FernsProvider.tsx
  packages/ui/src/IconButton.tsx
  packages/ui/src/Modal.tsx
  packages/ui/src/SegmentedControl.tsx
  packages/ui/src/SplitPage.native.tsx
  packages/ui/src/Theme.tsx
  packages/ui/src/Toast.tsx
  packages/ui/src/Tooltip.tsx
  packages/ui/src/Unifier.ts
  packages/ui/src/Utilities.tsx
  packages/ui/src/table/Table.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#625 EmailField, PhoneNumberField, and clean up Field
  apps/demo/demoConfig.tsx
  apps/demo/stories/EmailField.stories.tsx
  apps/demo/stories/Field.stories.tsx
  apps/demo/stories/PhoneNumberField.stories.tsx
  apps/demo/stories/index.ts
  apps/demo/story-config/EmailField.config.tsx
  apps/demo/story-config/Field.config.tsx
  apps/demo/story-config/PhoneNumberField.config.tsx
  apps/demo/story-config/index.ts
  packages/ui/src/Common.ts
  packages/ui/src/EmailField.tsx
  packages/ui/src/Field.tsx
  packages/ui/src/FieldWithLabels.tsx
  packages/ui/src/NumberField.tsx
  packages/ui/src/PhoneNumberField.tsx
  packages/ui/src/TextField.tsx
  packages/ui/src/Theme.tsx
  packages/ui/src/WithLabel.tsx
  packages/ui/src/index.tsx
Labels: enhancement, Review effort [1-5]: 3, Tests

#597 New Banner
  apps/demo/stories/Banner.stories.tsx
  apps/demo/story-config/Banner.config.tsx
  packages/ui/src/Banner.tsx
  packages/ui/src/Common.ts
  packages/ui/src/DismissButton.tsx
  packages/ui/src/index.tsx
Labels: Review effort [1-5]: 4, enhancement, documentation

#615 Table Theme, Badge, Table Badge, Table Text
  apps/demo/app/_layout.tsx
  apps/demo/app/demo/[component].tsx
  apps/demo/app/dev/index.tsx
  apps/demo/app/index.tsx
  apps/demo/demoConfig.tsx
  apps/demo/stories/Badge.stories.tsx
  apps/demo/stories/Table.stories.tsx
  apps/demo/stories/TableBadge.stories.tsx
  apps/demo/stories/TableNumber.stories.tsx
  apps/demo/stories/TableText.stories.tsx
  apps/demo/stories/TableTextField.stories.tsx
  apps/demo/stories/index.ts
  apps/demo/story-config/TableBadge.config.tsx
  apps/demo/story-config/TableNumber.config.tsx
  apps/demo/story-config/TableText.config.tsx
  apps/demo/story-config/index.ts
  packages/ui/src/Badge.tsx
  packages/ui/src/BlurBox.native.tsx
  packages/ui/src/BlurBox.tsx
  packages/ui/src/Common.ts
  packages/ui/src/IconButton.tsx
  packages/ui/src/PickerSelect.tsx
  packages/ui/src/SplitPage.native.tsx
  packages/ui/src/SplitPage.tsx
  packages/ui/src/TapToEdit.tsx
  packages/ui/src/Theme.tsx
  packages/ui/src/index.tsx
  packages/ui/src/table/Table.tsx
  packages/ui/src/table/TableBadge.tsx
  packages/ui/src/table/TableBoolean.tsx
  packages/ui/src/table/TableDate.tsx
  packages/ui/src/table/TableHeaderCell.tsx
  packages/ui/src/table/TableIconButton.tsx
  packages/ui/src/table/TableNumber.tsx
  packages/ui/src/table/TableRow.tsx
  packages/ui/src/table/TableText.tsx
  packages/ui/src/table/TableTextField.tsx
  packages/ui/src/table/TableTitle.tsx
Labels: enhancement, Review effort [1-5]: 3, Tests

#623 Add address demo, fix styling
  apps/demo/demoConfig.tsx
  apps/demo/stories/AddressField.stories.tsx
  apps/demo/stories/index.ts
  apps/demo/story-config/AddressField.config.tsx
  apps/demo/story-config/index.ts
  packages/ui/src/AddressField.tsx
  packages/ui/src/Common.ts
  packages/ui/src/Field.tsx
  packages/ui/src/FieldElements/FieldTitle.tsx
  packages/ui/src/SelectField.tsx
  packages/ui/src/TapToEdit.tsx
  yarn.lock
Labels: enhancement, Review effort [1-5]: 3, Tests

#629 Fix up field types
  packages/ui/src/AddressField.tsx
  packages/ui/src/Common.ts
  packages/ui/src/Field.tsx
  packages/ui/src/SelectList.tsx
  packages/ui/src/TapToEdit.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#627 New custom select
  apps/demo/app/demo/[component].tsx
  apps/demo/demoConfig.tsx
  apps/demo/stories/CustomSelectField.stories.tsx
  apps/demo/stories/index.ts
  apps/demo/story-config/Banner.config.tsx
  apps/demo/story-config/CustomSelectField.config.tsx
  apps/demo/story-config/index.ts
  packages/ui/src/Common.ts
  packages/ui/src/CustomSelect.tsx
  packages/ui/src/CustomSelectField.tsx
  packages/ui/src/Field.tsx
  packages/ui/src/TextField.tsx
  packages/ui/src/index.tsx
Labels: enhancement, documentation, Review effort [1-5]: 3, Tests

#624 Add navigation variant & indicators for IconButton
  apps/demo/stories/Badge.stories.tsx
  apps/demo/stories/IconButton.stories.tsx
  apps/demo/story-config/IconButton.config.tsx
  packages/ui/src/Badge.tsx
  packages/ui/src/Common.ts
  packages/ui/src/DateTimeActionSheet.tsx
  packages/ui/src/Heading.tsx
  packages/ui/src/IconButton.tsx
  packages/ui/src/MobileAddressAutoComplete.tsx
  packages/ui/src/Text.tsx
  packages/ui/src/TextField.tsx
  packages/ui/src/Theme.tsx
  packages/ui/src/table/TableNumber.tsx
  packages/ui/src/table/TableText.tsx
  packages/ui/src/table/TableTitle.tsx
Labels: enhancement, Review effort [1-5]: 3, Tests

#628 Add pagination
  apps/demo/stories/Pagination.stories.tsx
  apps/demo/stories/index.ts
  apps/demo/story-config/Pagination.config.tsx
  packages/ui/src/Common.ts
  packages/ui/src/Pagination.tsx
  packages/ui/src/index.tsx
  packages/ui/src/table/Table.tsx
Labels: Review effort [1-5]: 4, enhancement, documentation

#630 New tap to edit - WIP
  apps/demo/stories/TapToEdit.stories.tsx
  packages/ui/src/Common.ts
Labels: enhancement, Review effort [1-5]: 3, Tests

#674 Fix fullWidth button with tooltip
  apps/demo/stories/Button.stories.tsx
  packages/ui/src/Tooltip.tsx
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#675 updated tap to edit
  apps/demo/stories/TapToEdit.stories.tsx
  apps/demo/story-config/TapToEdit.config.tsx
  packages/ui/src/Common.ts
  packages/ui/src/TapToEdit.tsx
Labels: enhancement, documentation, Review effort [1-5]: 3

#673 Allow custom colors for Badge, other fixes
  apps/demo/stories/Accordion.stories.tsx
  apps/demo/stories/Badge.stories.tsx
  apps/demo/stories/Modal.stories.tsx
  packages/ui/src/Accordion.tsx
  packages/ui/src/Badge.tsx
  packages/ui/src/Button.tsx
  packages/ui/src/Common.ts
  packages/ui/src/IconButton.tsx
  packages/ui/src/Modal.tsx
  packages/ui/src/SegmentedControl.tsx
  packages/ui/src/TapToEdit.tsx
Labels: enhancement, Review effort [1-5]: 2, Tests

#678 Fixes round 2
  apps/demo/stories/DateTimeField.stories.tsx
  packages/ui/src/Common.ts
  packages/ui/src/DateTimeActionSheet.tsx
  packages/ui/src/DateTimeField.tsx
  packages/ui/src/Field.tsx
  packages/ui/src/Page.tsx
  packages/ui/src/SelectField.tsx
  packages/ui/src/TapToEdit.tsx
Labels: enhancement, Review effort [1-5]: 2

#683 autofocus tap to edit when editing
  apps/demo/stories/TapToEdit.stories.tsx
  packages/ui/src/TapToEdit.tsx
Labels: enhancement, Review effort [1-5]: 2, Other

#682 Fix links in TapToEdit
  packages/ui/src/TapToEdit.tsx
Labels: Review effort [1-5]: 2, Bug fix

#685 Flip default for Avatar.hasBorder to false
  apps/demo/stories/Avatar.stories.tsx
  packages/ui/src/Avatar.tsx
Labels: enhancement, Review effort [1-5]: 2, Tests

#686 UI Fixes Round 3
  packages/ui/src/Box.tsx
  packages/ui/src/SegmentedControl.tsx
  packages/ui/src/Toast.tsx
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#689 fix bug with textfield and datetimeactionsheet values not in sync
  packages/ui/src/DateTimeField.tsx
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#692 Stop showing "loading font"
  packages/ui/src/Heading.tsx
  packages/ui/src/Text.tsx
Labels: enhancement, Review effort [1-5]: 2

#693 Add disabled state to multiselect
  apps/demo/stories/MultiselectField.stories.tsx
  packages/ui/src/Common.ts
  packages/ui/src/MultiselectField.tsx
Labels: enhancement, Review effort [1-5]: 2

#696 Make all button variants look disabled
  apps/demo/stories/Button.stories.tsx
  packages/ui/src/Button.tsx
Labels: enhancement, Review effort [1-5]: 2

#695 Set ports for UI
  apps/demo/package.json
Labels: enhancement, Review effort [1-5]: 1
