Repository FlourishHealth/ferns-ui, pull requests merged in 2024-10, with the labels that each got.

#742 fix invalid date issue when clearing value from date/time pickers + add watch script
  README.md
  package.json
  packages/ui/src/DateTimeField.tsx
Labels: bug_fix, enhancement, Review effort [1-5]: 2, documentation

#741 Group dependencies for dependabot
  .github/dependabot.yml
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#743 Ignore eslint 9
  .github/dependabot.yml
Labels: Review effort [1-5]: 1, configuration changes

#738 Remove DateTimeActionsSheet from DateTimeField when disabled
  apps/demo/package.json
  apps/demo/stories/DateTimeField.stories.tsx
  apps/demo/story-config/DateTimeField.config.tsx
  packages/ui/package.json
  packages/ui/src/DateTimeField.tsx
  yarn.lock
Labels: enhancement, Review effort [1-5]: 2

#757 Fix TextNode errors
  packages/ui/src/TextField.tsx
Labels: Review effort [1-5]: 2, Bug fix

#763 Fix District of Columbia capitalization
  packages/ui/src/Constants.ts
Labels: Review effort [1-5]: 1, documentation
