Repository FlourishHealth/ferns-ui, pull requests merged in 2024-05, with the labels that each got.

#527 Dependency updates
  package.json
  packages/ui-demo/package.json
  packages/ui-demo/webpack.config.js
  packages/ui/package.json
  patches/react-native-reanimated+3.6.3.patch
  yarn.lock
Labels: bug_fix, enhancement, Review effort [1-5]: 3

#529 Remove sidedrawer style patch
  packages/ui/src/SideDrawer.tsx
Labels: enhancement, Review effort [1-5]: 2

#540 Expo 51 upgrade
  packages/ui-demo/package.json
  packages/ui/package.json
  patches/react-native-reanimated+3.6.3.patch
  syncUiFromUiDemo.js
  yarn.lock
Labels: enhancement, Review effort [1-5]: 3

#542 Fix timezone/date bug
  packages/ui/src/DateUtilities.tsx
Labels: Review effort [1-5]: 2, Bug fix

#550 Fix time-only formatting error for mobile
  packages/ui/src/DateUtilities.tsx
Labels: Review effort [1-5]: 2, Bug fix

#552 Fix tap to edit
  packages/ui-demo/package.json
  packages/ui-demo/src/TapToEdit.stories.tsx
  packages/ui/src/TapToEdit.tsx
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#523 Add option to print only times for date ranges
  packages/ui/src/DateUtilities.test.ts
  packages/ui/src/DateUtilities.tsx
  yarn.lock
Labels: enhancement, Review effort [1-5]: 2

#554 Fix drawer overflow scroll on web
  packages/ui/src/SideDrawer.tsx
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#556 Fix expo dependency
  packages/ui/package.json
  yarn.lock
Labels: dependencies, Review effort [1-5]: 1

#563 Fix another instance of timezones breaking
  packages/ui/src/DateUtilities.tsx
Labels: Review effort [1-5]: 2, Bug fix

#565 Fix textarea tap to edit again
  packages/ui/src/TapToEdit.tsx
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#567 Add web drawer scroll
  packages/ui/src/SideDrawer.tsx
Labels: enhancement, Review effort [1-5]: 2
