Repository FlourishHealth/ferns-ui, pull requests merged in 2025-03, with the labels that each got.

#833 Dependency updates and Expo 52
  apps/.DS_Store
  apps/demo/package.json
  apps/demo/yarn.lock
  packages/ui/package.json
  yarn.lock
Labels: Review effort 2/5

#842 Expanded segmented control
  apps/demo/stories/SegmentedControl.stories.tsx
  apps/demo/story-config/SegmentedControl.config.tsx
  packages/ui/src/Common.ts
  packages/ui/src/SegmentedControl.tsx
Labels: Review effort 2/5

#795 Allow text input for DateTimeField
  apps/demo/stories/DateTimeField.stories.tsx
  apps/demo/stories/Field.stories.tsx
  packages/ui/package.json
  packages/ui/src/Common.ts
  packages/ui/src/DateTimeActionSheet.tsx
  packages/ui/src/DateTimeField.tsx
  packages/ui/src/DateUtilities.tsx
  packages/ui/src/Field.tsx
  packages/ui/src/TimezonePicker.tsx
  yarn.lock
Labels: Review effort [1-5]: 4

#856 Change table boolean to red from gray
  packages/ui/src/table/TableBoolean.tsx
Labels: Review effort 1/5

#854 Fix DateTimeField, add tests
  apps/demo/stories/DateTimeField.stories.tsx
  packages/ui/babel.config.js
  packages/ui/jest-setup.js
  packages/ui/jest.config.js
  packages/ui/package.json
  packages/ui/src/DateTimeActionSheet.tsx
  packages/ui/src/DateTimeField.test.tsx
  packages/ui/src/DateTimeField.tsx
  packages/ui/src/setupTests.ts
  yarn.lock
Labels: Review effort 3/5
